export const platformNameMap: Record<string, string> = {
  'Netflix': 'Netflix',
  'Amazon Prime Video': 'Amazon Prime',
  'Prime Video': 'Amazon Prime',
  'Amazon Video': 'Amazon Prime',
  'Apple TV+': 'Apple TV+',
  'Apple TV': 'Apple TV+',
  'Disney Plus': 'Disney+',
  'Disney+': 'Disney+',
  'HBO Max': 'HBO Max',
  'Max': 'HBO Max',
  'Hulu': 'Hulu',
  'Peacock': 'Peacock',
  'Peacock Premium': 'Peacock',
  'Paramount Plus': 'Paramount+',
  'Paramount+': 'Paramount+',
  'AMC+': 'AMC+',
  'AMC+ Amazon Channel': 'AMC+',
  'AMC Plus Apple TV Channel': 'AMC+',
  'AMC+ Roku Premium Channel': 'AMC+'
};
