export const platformNameMap: Record<string, string> = {
  'Netflix': 'Netflix',
  'Amazon Prime Video': 'Amazon Prime',
  'Amazon Video': 'Amazon Prime',
  'Apple TV+': 'Apple TV+',
  'Apple TV': 'Apple TV+',
  'Disney Plus': 'Disney+',
  'Disney+': 'Disney+',
  'HBO Max': 'HBO Max',
  'Hulu': 'Hulu',
  'Peacock': 'Peacock',
  'Paramount Plus': 'Paramount+',
  'Paramount+': 'Paramount+',
  'YouTube': 'YouTube',
  'Google Play Movies': 'Google Play',
  'Microsoft Store': 'Microsoft',
  'Philo': 'Philo',
  'Kanopy': 'Kanopy',
  'AMC+': 'AMC+',
  'AMC+ Amazon Channel': 'AMC+',
  'AMC Plus Apple TV Channel': 'AMC+',
  'AMC+ Roku Premium Channel': 'AMC+',
  'IFC Films Unlimited': 'IFC Films',
  'The Roku Channel': 'Roku'
};
